version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - "echo [PACE_BUDDY_PIPELINE_SYSTEM]:: START_PRE_BUILD"
      - 'docker login --username=$DOCKER_ID --password=$DOCKER_PW'
  build:
    commands:
      - "echo [PACE_BUDDY_PIPELINE_SYSTEM]:: START_MAIN_BUILD"
      - "docker-compose -f docker-compose.yml build"
  post_build:
    commands:
      - "echo [PACE_BUDDY_PIPELINE_SYSTEM]:: START_POST_BUILD"
      - "docker-compose -f docker-compose.yml push"

artifacts:
  files:
    - "**/*"
#    - "appspec.yml"
#    - "scripts/*"
#    - "docker-compose.yml"
#    - "Dockerfile"
#    - "dist/*"