version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - "echo Build Phase >> pre_build phase..."
      - 'docker login --username=$DOCKER_ID --password=$DOCKER_PW'
  build:
    commands:
      - "echo Build Starting"
      - "docker-compose -f docker-compose.yml build"
  post_build:
    commands:
      - "echo post_Build Starting"
      - "docker-compose -f docker-compose.yml push"

artifacts:
  files:
    - "appspec.yml"
    - "scripts/*"
    - "docker-compose.yml"