#version: '3'
#services:
#  app:
#    image: thd930308/node:pace-buddy
#    build:
#      dockerfile: Dockerfile
#      context: .
#    container_name: "pacebuddy"
#    ports:
#      - 3000:3000
#    working_dir: /app
#    volumes:
#      - ./:/app
#    command: sh -c "npm install && npm run build && npm run start:prod"


version: "3"
services:
  app:
    restart: always
    image: thd930308/node:pace-buddy
    build:
      dockerfile: Dockerfile
      context: .
    container_name: "pacebuddy"
    volumes:
      - node_modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: