version: '3'
services:
  app:
    image: thd930308/node:pace-buddy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - node_modules:/app/node_modules

volumes:
  node_modules: