version: '3'
services:
  app:
    image: node:12-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run start"